.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC 
    MOV AH, 2   ;READY TO PRINT CHARACTER
    MOV CX, 256 ; LOOP COUNTER
    MOV DL, 0   ;INITIALIZATION
    
    PRINT_LOOP:
        INT 21H
        INC DL
        DEC CX
        JNZ PRINT_LOOP
    
    EXIT:
    MOV AH, 4CH
    INT 21H
    MAIN ENDP
END MAIN